name: Test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create test env file
        run: |
          cp .env.example .env
          perl -pi -e 's/=""/="test"/g' .env

      - name: Run tests
        run: bun test

      - name: Run type check and linting
        run: bun run check
